# Site settings
title: "Mark Halonen"
description: "Mark Halonen Michigan Software Engineer Developer"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Mark Halonen"
resume_title:                   "Freelance Software Developer"
resume_contact_email:
  "halonen.mark@gmail.com"
resume_header_contact_info: "942A Prospect St Hancock MI | 248-675-9529 | halonen.mark@gmail.com"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/markhalonen"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/mark-halonen-31a923b3/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://markhalonen.wordpress.com/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

gems:
  - jekyll-seo-tag
# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
